print ("")
print ("")
print ("")
name = input ("What is your name?")
print (f"Hi {name} and today we will do a fill in the blanks story")
print ("")
print ("")
weather = input ("choose the weather:")
animal = input ("Pick an animal")
location = input ("Now pick a location:")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print (f"One day, on a {weather} day, an {animal} wandered into a {location}")
