print ("")
print ("")
print ("")
name = input ("What is your name?")
print (f"Hi {name}!")
print ("today we will do a fill in the blanks story")
print ("")
print ("")
weather = input ("select the weather:")
animal = input ("Pick an animal:")
location = input ("Now pick a location:")
print ("")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print (f"One day, on a {weather} day, a {animal} wandered into a {location}")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print ("")
food = input ("Now choose a food:")
print ("")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print (f"Then, a treasure trove of {food} suddenly appeared and the {animal} walks curiously towards the mountain of {food}")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print ("")
animal2 = input ("Now choose another animal to guard the food:")
print ("")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print (f"Afterwards the {animal} spots a {animal2} closely guarding the pile of {food}")
print ("+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+")
print ("")